### ISSUE TITLE
Add a .Rproj file to the output of save_notebooks()

### ISSUE THREAD

**Issue by colearendt** [wlandau/learndrake#18]
For ease of training / changing working directories, it would be nice if the output of `save_notebooks()` had .Rproj files associated with the directories. Not sure if these are getting caught by .Rbuildignore or what.

**Comment by wlandau** [comment]
Thanks for tracking this down. Looks like it only happens when the package is installed from GitHub. The Rproj folders never appeared missing for me because I was always installing locally. Anyway, I modified `.gitignore` and `.Rbuildignore` to try to address it. Does it work on your end now?

**Comment by colearendt** [comment]
Yeah, looks good now! Thanks!

**Comment by wlandau** [comment]
Great!
