### ISSUE TITLE
save_app is not idempotent

### ISSUE THREAD

**Issue by colearendt** [wlandau/learndrake#19]
`save_app()` in a blank directory creates a `learndrakeflow` folder. `save_app()` again creates a folder `learndrakeflow/learndrakeflow` with a new copy of the app.  And `save_app()` again errors. (behaves similarly for other apps)

It may be worth ensuring that the `save_app()` function behaves a bit nicer if you have already executed it. Not sure whether the best behavior is to error, warn, overwrite, or diff / update / etc.

(Note: the HELP for the save_app() function is out of date as well).

**Comment by wlandau** [comment]
Thanks! Now fixed.

**Comment by wlandau** [comment]
FYI: I decided to throw an error if the directory already exists.
