### ISSUE TITLE
Use cancer immunotherapy example

### ISSUE THREAD

**Issue by wlandau-lilly** [wlandau/learndrake#23]
## Prework

- [x] Read and abide by `drake`'s [code of conduct](https://github.com/wlandau/learndrake/blob/master/CODE_OF_CONDUCT.md).
- [x] Search for duplicates among the [existing issues](https://github.com/wlandau/learndrake/issues), both open and closed.

## Description

https://github.com/leonjessen/RPharma2019/blob/master/Exercises/05_deep_learning_for_cancer_immunotherapy.Rmd. Seems like stronger motivation than the current example.

**Comment by wlandau** [comment]
Thought about it, and it's an excellent example, but I do not have time for the kind of work it would take to overhaul the entire workshop. Plus, the telecom dataset is easier to understand, which will allow people to get straight to learning `drake` more quickly.
