### ISSUE TITLE
Emphasize more examples of long computation in the slides

### ISSUE THREAD

**Issue by wlandau** [wlandau/learndrake#26]
## Prework

- [x] Read and abide by `drake`'s [code of conduct](https://github.com/wlandau/learndrake/blob/master/CODE_OF_CONDUCT.md).
- [x] Search for duplicates among the [existing issues](https://github.com/wlandau/learndrake/issues), both open and closed.

## Description

The motivating use case in the notebooks and apps may not resonate with everyone (related: #23) especially in some of the industry conferences I plan to present at this year. So the slides should stress where practical use cases come up.

**Comment by wlandau-lilly** [comment]
Done.
