### ISSUE TITLE
Redeploy to RStudio Cloud

### ISSUE THREAD

**Issue by wlandau** [wlandau/learndrake#29]
## Prework

- [x] Read and abide by `drake`'s [code of conduct](https://github.com/wlandau/learndrake/blob/master/CODE_OF_CONDUCT.md).
- [x] Search for duplicates among the [existing issues](https://github.com/wlandau/learndrake/issues), both open and closed.

## Description

I am having trouble redeploying the notebooks to RStudio Cloud, re https://community.rstudio.com/t/persistent-python-environment-for-rstudio-cloud-projects/52350 and https://community.rstudio.com/t/trouble-setting-up-tensorflow-on-rstudio-cloud/52349. It is difficult to get Python TensorFlow to install properly.

**Comment by wlandau** [comment]
Waiting for https://github.com/rstudio/rstudio/issues/6049.

**Comment by wlandau-lilly** [comment]
Now fixed by downgrading TensorFlow, making sure to set `tensorflow = "1.13.1"` in `install_keras()`.
